apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  
  selector:
    matchLabels:
      app: flask-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: jmpberlin/flask-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app
#   labels:
#     app: flask-app
# spec:
#   type: LoadBalancer
#   selector:
#     app: flask-app
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP