apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
spec:
  selector:
    matchLabels:
      app: py-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app
          image: jmpberlin/py-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  type: LoadBalancer
  selector:
    app: py-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
