version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  create-deployment:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          flask-app
        type: string
      aws-region:
        description:  |
          us-east-1
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment-config.yml
          resource-name: deployment/flask-app
workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: flask-app
      - create-deployment:
          cluster-name: flask-app
          aws-region: us-east-1
          requires:
            - aws-eks/create-cluster
      - aws-eks/update-container-image:
          cluster-name: flask-app
          container-image-updates: 'flask-app=jmpberlin/flask-app'
          post-steps:
            - kubernetes/delete-resource:
                resource-names: flask-app
                resource-types: deployment
                wait: true
          requires:
            - create-deployment
          resource-name: deployment/flask-app
      # - aws-eks/delete-cluster:
      #     cluster-name: flask-app
      #     requires:
      #       - aws-eks/update-container-image